### ISSUE TITLE
work great but dont show mute and deafen

### ISSUE THREAD

**Issue by Otooooo** [Naozumi520/Remedy#11]
work great but dont show mute and deafen
<img width="82" alt="Capture d’écran 2022-12-07 à 13 47 11" src="https://user-images.githubusercontent.com/115180163/206183121-be26f774-448a-4c7c-b908-666a022a38e1.png">
<img width="202" alt="Capture d’écran 2022-12-07 à 13 47 09" src="https://user-images.githubusercontent.com/115180163/206183131-cd2b8e69-4e96-45c5-94a3-2155e349bc49.png">

**Comment by Naozumi520** [comment]
Hi, have you tried resetting the program (open setting menu) to see if that fixes the issue? If not, you may want to try that and see if the icons appear afterwards.

**Comment by DronePT** [comment]
Hi @Naozumi520 , I think streamkit html has changed, you're using `data-reactid` attribute to match the user span, but I think they are not using `data-reactid` anymore and also there is no `.voice-container` css classes anymore.

**Comment by Naozumi520** [comment]
> Hi @Naozumi520 , I think streamkit html has changed, you're using `data-reactid` attribute to match the user span, but I think they are not using `data-reactid` anymore and also there is no `.voice-container` css classes anymore.

Thanks for telling me this! I'm a bit busy with school, so I don't know this. I've fixed these issues and will post a new version later. 😄

**Comment by Naozumi520** [comment]
Fixed in release [1.1.6](https://github.com/Naozumi520/Remedy/releases/tag/RemedyPro1.1.6), please check out.

**Comment by Naozumi520** [comment]
Close as fixed
