### ISSUE TITLE
Arm64

### ISSUE THREAD

**Issue by damonemo** [Naozumi520/Remedy#12]
When I downloaded the arm64 one I get this message. 

<img width="261" alt="Screenshot 2022-12-28 at 9 06 48 AM" src="https://user-images.githubusercontent.com/75283377/209824517-fc688ea4-b57c-4623-8d33-0cff6df814fe.png">

**Comment by Naozumi520** [comment]
It seems that electron-builder has issue building arm64 app. I can try build a universal version later so Remedy will work on both x64 and arm64. But package size is going to be an issue, and has been around for a long time as well... 😭

**Comment by Naozumi520** [comment]
Can you try this package (1.1.8 pre-release)?

https://cdn.discordapp.com/attachments/939482444778864663/1079079296901054484/Remedy_Pro-1.1.7-universal.dmg.zip

**Comment by damonemo** [comment]
It works

**Comment by Naozumi520** [comment]
Nice! I will publish this version then. 😋

**Comment by damonemo** [comment]
OK wait it's not working. The overlay is not working but the app and login
works if that makes sense

**Comment by Naozumi520** [comment]
Hmm, can you try restarting the app and try again? I got it once during testing, but couldn't reproduce it.

**Comment by Naozumi520** [comment]
Ah, I see the problem. Will be fixed in release.

**Comment by damonemo** [comment]
Do you have the fix version?

**Comment by Naozumi520** [comment]
Not yet. But the problem has been confirmed and I'm going to fix it when I have the time.

**Comment by Naozumi520** [comment]
Hello! I released the version [1.1.8](https://github.com/Naozumi520/Remedy/releases/tag/RemedyPro1.1.8), which includes all the fixes, please take a look!

Edited: Hold on, I'm sorry that the app got some issue after packing. I will keep you update asap!

**Comment by damonemo** [comment]
you didn't put the download up '-'

**Comment by Naozumi520** [comment]
Yep, the app got some issue after packing. I will keep you update ASAP.

**Comment by damonemo** [comment]
1.1.2 should be the one I download correct?

**Comment by Naozumi520** [comment]
Yes, 1.1.2 is the updated standard version. Pro version is now having issue.

**Comment by Naozumi520** [comment]
Fixed in 2.0
