### ISSUE TITLE
Allow for group chats and dm calls

### ISSUE THREAD

**Issue by Modularizable** [Naozumi520/Remedy#4]
Is it possible to have overlay in group chats and private calls?

**Comment by Naozumi520** [comment]
Yes, I saw [this video](https://www.youtube.com/watch?v=g-m6Q-oQZs8) and it's relates to #3

**Comment by Naozumi520** [comment]
All the tasks are done! I'll check it out in tomorrow 😁

**Comment by Naozumi520** [comment]
Will be added in the next release! (Pro version) 🎉

**Comment by UltraModular** [comment]
Thank you! 😄👍

**Comment by Naozumi520** [comment]
[Release 1.1.x](https://github.com/Naozumi520/Remedy/releases/) is now release and it should now work no matter what type of voice channel you're in 😁

Please let me know if you've tried it and confirmed it always works!

**Comment by UltraModular** [comment]
Thank you for your hard work! It works now! 🎉 One issue though is that it only stays for a minute and so but then disappears. I don't know if this is an issue with your app though (I'm using the desktop app). Thank you for your excellent work so far! (This is in Remedy 1.1.2 by the way)

https://user-images.githubusercontent.com/98797598/179480397-7a79b698-9a93-4a5b-bec0-a662ea34b3ff.mp4

**Comment by Naozumi520** [comment]
I see. Does it only happen on this version or all the versions as well? If yes, what was the first version that it worked?
🤔I have never seen such problem in before... 
Maybe you could add my discord? It's `Naozumi#0233`. Let's see if I could help on this problem.

**Comment by Naozumi520** [comment]
@Modularizable
I've released version [1.1.3](https://github.com/Naozumi520/Remedy/releases/tag/RemedyPro) and there are many changes like updated packages.
Please tell me if it fixes the issue. 😆

**Comment by UltraModular** [comment]
Thank you! [Remedy 1.1.3](https://github.com/Naozumi520/Remedy/releases/tag/RemedyPro) works! Keep up with the hard work!😄 🎉
