### ISSUE TITLE
Remedy Pro arm64 "is damaged" according to macOS

### ISSUE THREAD

**Issue by jaredklett** [Naozumi520/Remedy#9]
Tried both the 1.1.4 and 1.1.5 dmg downloads. Dragged the app to the Applications folder shortcut. Launched the app. Got an alert that the app "is damaged", will attach a screenshot.

macOS Monterey
12.5.1 (21G83)
MacBook Pro (16-inch, 2021)
Apple M1 Pro

<img width="300" alt="Screen Shot 2022-10-05 at 13 06 06" src="https://user-images.githubusercontent.com/1318946/194120104-fabf5776-73a3-44cf-a391-36f35f70eea7.png">

**Comment by Naozumi520** [comment]
For some reasons I was not able to sign for the app, however you can still tell macOS to trust such apps with command `sudo xattr -rd com.apple.quarantine /Applications/[LockedApp].app`

In this case `[LockedApp].app` should be `Remedy\ Pro.app`.
`sudo xattr -rd com.apple.quarantine /Applications/Remedy\ Pro.app `

More info: https://apple.stackexchange.com/questions/262355/xxx-cant-be-opened-you-should-move-it-to-trash-for-flash-projector-applicat

Please report back if it works or failed 😬
